version: '3.7'
services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
    depends_on:
      - api
    ports:
      - 3000:3000
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - 8000:8000