version: '3.7'
services:
  app:
    image: node:lts-alpine
    working_dir: /app
    entrypoint: /bin/sh
    command: /app/start.sh
    volumes:
      - ./app-programas-estudos:/app
    depends_on:
      - api
    ports:
      - 3000:3000
  api:
    image: php:7-alpine
    working_dir: /var/www
    entrypoint: /bin/sh
    command: /app/start.sh
    environment:
      docker: "true"
    ports:
      - 8000:8000
    volumes:
      - ./api-programa-estudos:/var/www
      - ./api-programa-estudos/logs:/var/www/logs